# Generated by Django 3.2.3 on 2021-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210707_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='name',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
